# Generated by Django 2.1.2 on 2018-11-02 08:05

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chäř')),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('logic', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('decimal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('float', models.FloatField(blank=True, null=True)),
                ('bigint', models.BigIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('nullable', models.CharField(default=None, max_length=255, null=True)),
                ('choices', models.IntegerField(blank=True, choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3')], null=True)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
