name: Test

on:
    push:
        branches:
            - master
            - develop
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-python@v2

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip flake8 isort
            -   name: Lint with flake8
                run: |
                    flake8 src
                    isort -c src
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [ "3.8", "3.9", "3.10" ]
                django-version: [ "3.2", "4.0" ]
                drf-version: [ "3.12", "3.13" ]
        env:
            PY_VER: ${{ matrix.python-version}}
            DJ_VER: ${{ matrix.django-version}}
            DRF_VER: ${{ matrix.drf-version}}

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: python -m pip install --upgrade pip tox

            -   name: Test with
                run: tox -e "py${PY_VER//.}-d${DJ_VER//.}-drf${DRF_VER//.}"

            -   uses: codecov/codecov-action@v1
                with:
                    verbose: true
